language: node_js

node_js:
- node

before_install: npm install -g hexo-cli

install: npm install

script:
    git submodule init

    git submodule update

    hexo clean

    hexo generate

after_success: 
  git config --global user.name "shibing"

  git config --global user.email "shibing.sw@139.com"

  hexo deploy
